CREATE TABLE umkm (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  nama_usaha VARCHAR(200) NOT NULL,
  pemilik VARCHAR(100) NOT NULL,
  nik_pemilik VARCHAR(16),
  no_hp VARCHAR(20),
  alamat_usaha TEXT,
  jenis_usaha VARCHAR(50) NOT NULL,
  kategori_usaha VARCHAR(50),
  deskripsi_usaha TEXT,
  produk TEXT,
  kapasitas_produksi INTEGER DEFAULT 0,
  satuan_produksi VARCHAR(50),
  periode_operasi INTEGER DEFAULT 0,
  satuan_periode VARCHAR(20) DEFAULT 'bulan',
  hari_kerja_per_minggu INTEGER DEFAULT 0,
  total_produksi INTEGER DEFAULT 0,
  rab BIGINT DEFAULT 0,
  biaya_tetap BIGINT DEFAULT 0,
  biaya_variabel BIGINT DEFAULT 0,
  modal_awal BIGINT DEFAULT 0,
  target_pendapatan BIGINT DEFAULT 0,
  jumlah_karyawan INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'Aktif',
  tanggal_daftar TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
